services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: LOG_LEVEL
        value: info
      - key: MONGODB_URI
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
